format_version: 3
pipelines:
  hello_github:
    group: test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/gocd-contrib/getting-started-repo
        shallow_clone: true
        auto_update: false
        branch: master
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          default_job:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
