format_version: 3
environments:
  prod:
    pipelines:
      - app2_prod
pipelines:
  app2_prod:
    group: app2
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/lspas-volvo/environments.git
        shallow_clone: true
        auto_update: true
        branch: master
        whitelist:
          - 'app2/prod.*'
          - 'app2/prod-*'
          - 'app2/prod_*'
          - 'app2/prod/*'
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          default_job:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
